---
- name: enable ports
  firewalld: >
    port={{ item }}
    zone={{ firewalld_zone }}
    permanent=true
    state=enabled
    immediate=yes
  with_items: firewalld_ports

- name: enable services
  firewalld: >
    service={{ item }}
    zone={{ firewalld_zone }}
    permanent=true
    state=enabled
    immediate=yes
  with_items: firewalld_services
